default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/base-angewandte/pre-commit-hooks
    rev: 1.3.0
    hooks:
      - id: base-hooks
      - id: base-commit-msg-hooks
